# Generated by Django 4.1 on 2022-08-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_output', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoutput',
            name='sold_price',
            field=models.DecimalField(db_column='sold_price', decimal_places=2, default=1.5, max_digits=7),
            preserve_default=False,
        ),
    ]
