# Generated by Django 4.1 on 2022-08-24 13:01

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_output', '0002_productoutput_sold_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoutput',
            name='quantity',
            field=models.IntegerField(db_column='quantity', default=0, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='productoutput',
            name='sold_price',
            field=models.DecimalField(db_column='sold_price', decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
