# Generated by Django 4.1 on 2022-08-25 12:45

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_output', '0003_alter_productoutput_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoutput',
            name='quantity',
            field=models.IntegerField(db_column='quantity', default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='productoutput',
            name='sold_price',
            field=models.DecimalField(db_column='sold_price', decimal_places=2, default=0.01, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
