# Generated by Django 4.1 on 2022-08-25 18:13

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_output', '0004_alter_productoutput_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoutput',
            name='sold_price',
            field=models.DecimalField(db_column='sold_price', decimal_places=2, default=1, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
