# Generated by Django 3.2.13 on 2022-06-22 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corporate_name', models.CharField(db_column='corporate_name', max_length=128)),
                ('fantasy_name', models.CharField(db_column='fantasy_name', default='', max_length=128)),
                ('created', models.DateField(db_column='created')),
                ('cnpj', models.CharField(db_column='cnpj', max_length=14, unique=True)),
                ('email', models.EmailField(db_column='email', default='', max_length=254)),
                ('phone_number', models.CharField(db_column='phone_number', default='', max_length=32)),
            ],
        ),
    ]
