version: '3.4'

services:
  postgres:
    container_name: db_projeto_integrador
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bar
    ports:
      - "127.0.0.1:7438:5432"
    restart: always
    volumes:
      - database_data:/var/lib/postgresql/data/

volumes:
  database_data:
