version: '3.4'

services:
  postgres:
    container_name: db_projeto_integrador
    image: postgres:14.3
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${DB_PORT}
    restart: always
    volumes:
      - database_data:/var/lib/postgresql/data/

volumes:
  database_data:
