# Generated by Django 3.2.13 on 2022-07-21 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selling_date', models.DateTimeField(db_column='selling_date')),
                ('payment_form', models.CharField(db_column='payment_form', default='cash', max_length=32)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('client_id', models.ForeignKey(db_column='client_id', on_delete=django.db.models.deletion.DO_NOTHING, to='client.client')),
            ],
        ),
    ]
