# Generated by Django 4.1 on 2022-08-25 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_payment_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_form',
            field=models.CharField(db_column='payment_form', default='Dinheiro', max_length=32, null=True),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['is_active'], name='order_order_is_acti_84d236_idx'),
        ),
    ]
