# Generated by Django 3.2.13 on 2022-07-21 14:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillsToBeReceived',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inclusion_date', models.DateTimeField(db_column='inclusion_date', default=datetime.datetime(2022, 7, 21, 11, 48, 43, 409476))),
                ('remaining_value', models.DecimalField(db_column='remaining_value', decimal_places=2, max_digits=7)),
                ('order_id', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.DO_NOTHING, to='order.order')),
            ],
        ),
    ]
