# Generated by Django 4.1 on 2022-08-24 12:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills_tobe_received', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billstobereceived',
            name='inclusion_date',
            field=models.DateField(db_column='inclusion_date', default=datetime.date.today),
        ),
    ]
