# Generated by Django 3.2.14 on 2022-08-25 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0002_alter_product_barcode_alter_product_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductIngredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(db_column='quantity')),
                ('ingredient', models.ForeignKey(db_column='ingredient', on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_set', to='product.product')),
                ('product', models.ForeignKey(db_column='product', on_delete=django.db.models.deletion.CASCADE, related_name='product_set', to='product.product')),
            ],
        ),
    ]
