# Generated by Django 3.2.13 on 2022-06-13 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(db_column='cep', default='', max_length=8)),
                ('street', models.CharField(db_column='street', default='', max_length=256)),
                ('number', models.IntegerField(db_column='number', null=True)),
                ('district', models.CharField(db_column='district', default='', max_length=256)),
                ('city', models.CharField(db_column='city', default='', max_length=256)),
                ('state', models.CharField(db_column='state', default='', max_length=2)),
            ],
        ),
    ]
