# Generated by Django 3.2.13 on 2022-07-21 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(db_column='full_name', max_length=128)),
                ('nickname', models.CharField(db_column='nickname', max_length=128, null=True)),
                ('birth_date', models.DateField(db_column='birth_date', null=True)),
                ('cpf', models.CharField(db_column='cpf', max_length=11, unique=True)),
                ('phone_number', models.CharField(db_column='phone_number', default='', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(db_column='cep', default='', max_length=8)),
                ('street', models.CharField(db_column='street', default='', max_length=256)),
                ('number', models.IntegerField(db_column='number', null=True)),
                ('district', models.CharField(db_column='district', default='', max_length=256)),
                ('city', models.CharField(db_column='city', default='', max_length=256)),
                ('state', models.CharField(db_column='state', default='', max_length=2)),
                ('client', models.ForeignKey(db_column='client_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='client.client')),
                ('supplier', models.ForeignKey(db_column='supplier_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier')),
            ],
        ),
    ]
