# Generated by Django 3.2.13 on 2022-06-13 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_column='name', max_length=128)),
                ('nickname', models.CharField(db_column='nickname', max_length=128, null=True)),
                ('birth_date', models.DateField(db_column='birth_date', null=True)),
                ('cpf', models.CharField(db_column='cpf', max_length=11, unique=True)),
                ('phone_number', models.CharField(db_column='phone_number', default='', max_length=32)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.address')),
            ],
        ),
    ]
