# Generated by Django 3.2.13 on 2022-06-22 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='first_name',
        ),
        migrations.AddField(
            model_name='client',
            name='full_name',
            field=models.CharField(db_column='full_name', default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='client',
            field=models.ForeignKey(db_column='client_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='client.client'),
        ),
    ]
