# Generated by Django 3.2.13 on 2022-07-21 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_entry_document', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillsToBePaid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_type', models.CharField(db_column='bill_type', default='', max_length=64)),
                ('installment_number', models.IntegerField(db_column='installment_number')),
                ('installment_value', models.DecimalField(db_column='installment_value', decimal_places=2, max_digits=7)),
                ('due_date', models.DateField(db_column='due_date')),
                ('is_paid', models.BooleanField(db_column='is_paid', default=False)),
                ('entry_document', models.ForeignKey(db_column='entry_document_id', on_delete=django.db.models.deletion.CASCADE, to='product_entry_document.entrydocument')),
            ],
        ),
    ]
