# Generated by Django 3.2.13 on 2022-07-21 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrillReserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_hour', models.DateTimeField(db_column='start_hour')),
                ('finish_hour', models.DateTimeField(db_column='finish_hour')),
                ('observation', models.CharField(db_column='observation', default='', max_length=512, null=True)),
                ('client_id', models.ForeignKey(db_column='client_id', on_delete=django.db.models.deletion.DO_NOTHING, to='client.client')),
            ],
        ),
    ]
